// Generated by Wrangler on Mon Aug 12 2024 02:01:46 GMT+0100 (West Africa Standard Time)
// by running `wrangler types --env-interface CloudflareEnv env.d.ts`

interface CloudflareEnv {
	ALCHEMY_API_KEY: string;
	NEXT_PUBLIC_ALCHEMY_API_KEY: string;
}
