name = "pathway"

main = "app/server.ts"

workers_dev = true
compatibility_date = "2023-04-20"

minify = true
node_compat = true

vars = {ENVIRONMENT = "production"}

route = { pattern = "app.thepathway.to", zone_name = "thepathway.to", custom_domain = true }

[site]
bucket = "build/client"