name = "pathway"

main = "./app/server.mjs"
assets = "./build/client"
workers_dev = true
compatibility_date = "2023-04-20"

minify = true
node_compat = true

route = { pattern = "thepathway.to", zone_name = "thepathway.to", custom_domain = true }