name = "pathway"

main = "app/server.ts"

workers_dev = true
compatibility_date = "2023-04-20"

minify = true
node_compat = true

route = { pattern = "app.thepathway.to", custom_domain = true }

[site]
bucket = "build/client"

[limits]
cpu_ms = 30000