[profile.default]
evm_version = 'paris'
via_ir = true
src = 'src'
out = 'out'
test = 'test'
libs = ['lib']
optimizer = true
optimizer_runs = 10_000_000
solc_version = "0.8.26"
remappings = [
    "ds-test/=lib/forge-std/lib/ds-test/src/",
    "forge-std/=lib/forge-std/src/",
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "@cctp/contracts=lib/evm-cctp-contracts/src",
]

[etherscan]
base = { key = "${BASESCAN_API_KEY}", chain = 8453, url = "https://api.basescan.org/api" }
avalanche = { key = "verifyContract", chain = 43114, url = "https://api.routescan.io/v2/network/mainnet/evm/43114/etherscan" }
fuji = { key = "verifyContract", chain = 43113, url = "https://api.routescan.io/v2/network/testnet/evm/43113/etherscan" }
sepolia = { key = "${ETHERSCAN_API_KEY}", chain = 11155111 }
