org: peteruche21
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: pathway
service: pathway

custom: ${file(./env.yml)}

stages:
  default:
    params:
      # sqs parameters
      executioQueueName: ${self:service}-${sls:stage}-execution-queue
      attestationQueueName: ${self:service}-${sls:stage}-attestation-queue
      relayQueueName: ${self:service}-${sls:stage}-relay-queue
      retryQueueName: ${self:service}-${sls:stage}-retry-queue
      # dynamodb parameters
      msgTableName: "${self:service}-${sls:stage}-messages"
      apiKeyTableName: "${self:service}-${sls:stage}-api-keys"
      # custom parameters
      pool_id: ${self:custom.poolId}
      client_id: ${self:custom.clientId}
      apitoolkitSecret: ${self:custom.apiToolkitSecret}
      destinationCallerApiKey: ${self:custom.destinationCallerApiKey}
      thirdwebSecret: ${self:custom.thirdwebSecret}

provider:
  name: aws
  runtime: nodejs20.x
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - Fn::GetAtt: [MessageTable, Arn]
            - Fn::GetAtt: [ApiKeyTable, Arn]

        - Effect: Allow
          Action:
            - sqs:SendMessage
            - sqs:ReceiveMessage
            - sqs:DeleteMessage
            - sqs:GetQueueUrl
          Resource:
            - Fn::GetAtt: [AttestationQueue, Arn]
            - Fn::GetAtt: [RelayQueue, Arn]
            - Fn::GetAtt: [RetryQueue, Arn]

  environment:
    MESSAGE_TABLE: ${param:msgTableName}
    API_KEY_TABLE: ${param:apiKeyTableName}
    EXECUTION_QUEUE_URL: https://sqs.${aws:region}.amazonaws.com/${aws:accountId}/${param:executioQueueName}
    ATTESTATION_QUEUE_URL: https://sqs.${aws:region}.amazonaws.com/${aws:accountId}/${param:attestationQueueName}
    RELAY_QUEUE_URL: https://sqs.${aws:region}.amazonaws.com/${aws:accountId}/${param:relayQueueName}
    RETRY_QUEUE_URL: https://sqs.${aws:region}.amazonaws.com/${aws:accountId}/${param:retryQueueName}
    APITOOLKIT_API_KEY: ${param:apitoolkitSecret}
    DESTINATION_CALLER_API_KEY: ${param:destinationCallerApiKey}
    THIRDWEB_SECRET: ${param:thirdwebSecret}

  httpApi:
    cors: true
    authorizers:
      lambdaAuthorizer:
        type: request
        functionName: authorizer
      jwtAuthorizer:
        type: jwt
        identitySource: $request.header.Authorization
        issuerUrl: https://cognito-idp.${aws:region}.amazonaws.com/${param:pool_id}
        audience:
          - ${param:client_id}

functions:
  authorizer:
    handler: src.authorizer.handler

  scheduler:
    handler: src.scheduler.handler
    events:
      - schedule: rate(2 minutes)

  api:
    handler: src.api.handler
    events:
      - httpApi:
          path: /message/new
          method: POST
          authorizer:
            name: lambdaAuthorizer
      - httpApi:
          path: /message/{partition_key}
          method: GET
          authorizer:
            name: lambdaAuthorizer
      - httpApi:
          path: /create-api-key
          method: POST
          authorizer:
            name: jwtAuthorizer

  execution:
    handler: src.execution.handler
    timeout: 120
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - ExecutionQueue
              - Arn
          functionResponseType: ReportBatchItemFailures
          batchSize: 10
          maximumBatchingWindow: 30

  attestation:
    handler: src.attestation.handler
    timeout: 120
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - AttestationQueue
              - Arn
          functionResponseType: ReportBatchItemFailures
          batchSize: 10
          maximumBatchingWindow: 30

  relay:
    handler: src.relay.handler
    timeout: 120
    memorySize: 1536
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - RelayQueue
              - Arn
          functionResponseType: ReportBatchItemFailures
          batchSize: 10
          maximumBatchingWindow: 30

  retry:
    handler: src.retry.handler
    timeout: 120
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - RetryQueue
              - Arn
          functionResponseType: ReportBatchItemFailures
          batchSize: 10
          maximumBatchingWindow: 30

resources:
  Resources:
    MessageTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: hash
            AttributeType: S
        KeySchema:
          - AttributeName: hash
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${param:msgTableName}

    ApiKeyTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: api_key
            AttributeType: S
        KeySchema:
          - AttributeName: api_key
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${param:apiKeyTableName}

    ExecutionQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${param:executioQueueName}
        VisibilityTimeout: 120

    AttestationQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${param:attestationQueueName}
        RedrivePolicy:
          deadLetterTargetArn:
            Fn::GetAtt:
              - RetryQueue
              - Arn
          maxReceiveCount: 5
        VisibilityTimeout: 120

    RelayQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${param:relayQueueName}
        RedrivePolicy:
          deadLetterTargetArn:
            Fn::GetAtt:
              - RetryQueue
              - Arn
          maxReceiveCount: 5
        VisibilityTimeout: 150

    RetryQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${param:retryQueueName}
        VisibilityTimeout: 120
